# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fe0b4d67c7a998dd8c40203571dd97fa3f1dd3fab03282ee0ae106dc5852909cbf1722cc24e87c57defe418112b1e5c233a094bf0eec55bd67b0b6226dfecc7

test:
  secret_key_base: 981803522b213a7162a0bbd4771fde701e6f788f1fc4a954ce46d512d759e003598d6575d139b3bc9db53ff0d33a92b66a2413460098c8f49364a726c779fad1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
